<?php
/**
 * TL_ROOT/system/modules/catalogajaxratingfield/languages/de/tl_catalog_fields.php 
 * 
 * Contao extension: cataloggeocoordsfield 0.1 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Nikolas Runde
 * License   : LGPL 
 * Author    : Nikolas Runde, http://www.nrmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['geocoordsfield'] = "Koordinatenfeld";

$GLOBALS['TL_LANG']['tl_catalog_fields']['geoCoordsTable'] = array("Adresstabelle","Tabelle die die ben&ouml;tigten Adressdaten enth&auml;lt");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_streetfield']= array("Stra&szlig;e und Hausnummer","Geben Sie hier das Feld f&uuml;r die Stra&szlig;e und Hausnummer an");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_postalfield'] = array("Postleitzahl","Geben Sie hier das Feld f&uuml;r die Postleitzahl an");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_cityfield'] = array("Ort","Geben Sie hier das Feld f&uuml;r den Ort an");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_countryfield']= array("Land","Geben Sie hier das Feld f&uuml;r das Land an");


$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_streetfield_rewrite'] = array("Wert berichtigen ?","Diese Eingabe mit der Google Antwort berichtigen");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_postalfield_rewrite'] = array("Wert berichtigen ?","Diese Eingabe mit der Google Antwort berichtigen");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_cityfield_rewrite'] = array("Wert berichtigen ?","Diese Eingabe mit der Google Antwort berichtigen");
$GLOBALS['TL_LANG']['tl_catalog_fields']['geocoords_countryfield_rewrite'] = array("Wert berichtigen ?","Diese Eingabe mit der Google Antwort berichtigen");